<?php
function headersection() {
echo "<!-- InstanceEndEditable --><!-- InstanceBeginEditable name=\"head\" --><!-- InstanceEndEditable -->\n"; 
echo "<style type=\"text/css\" media=\"all\">\n"; 
echo "<!--\n"; 
echo "@import url(\"styles.css\");\n"; 
echo "-->\n"; 
echo "</style>\n"; 
echo "<style type=\"text/css\" media=\"print\">\n"; 
echo "<!--\n"; 
echo "This is the stylesheet for web page printing. It is optional.\n"; 
echo "-->\n"; 
echo "<!--\n"; 
echo "@import url(\"print.css\");\n"; 
echo "-->\n"; 
echo "</style>\n"; 
echo "<!--[if IE 5]>\n"; 
echo "<style type=\"text/css\"> \n"; 
echo "#outerWrapper #contentWrapper #leftColumn1 {\n"; 
echo "  width: 200px;\n"; 
echo "}\n"; 
echo "#outerWrapper #contentWrapper #rightColumn1 {\n"; 
echo "  width: 200px;\n"; 
echo "}\n"; 
echo "</style>\n"; 
echo "<![endif]-->\n"; 
echo "<!--[if IE]>\n"; 
echo "<style type=\"text/css\"> \n"; 
echo "#outerWrapper #contentWrapper #content {\n"; 
echo "  zoom: 1; \n"; 
echo "}\n"; 
echo "</style>\n"; 
echo "<![endif]-->\n"; 
echo "<script type=\"text/javascript\" src=\"cssmw/cssmw/menu.js\"></script>\n"; 
echo "<!--[if lte IE 6]>\n";
echo "<link rel=\"stylesheet\" type=\"text/css\" media=\"all\" href=\"cssmw/cssmw/menu_ie.css\" />\n"; 
echo "<![endif]-->\n"; 
echo "<link rel=\"stylesheet\" type=\"text/css\" media=\"all\" href=\"cssmw/cssmw/menu.css\" />\n"; 
echo "<link rel=\"stylesheet\" media=\"screen,projection\" type=\"text/css\" href=\"scheme.css\" />\n"; 
echo "<link rel=\"stylesheet\" media=\"all\" type=\"text/css\" href=\"login.css\" />\n"; 
echo "<link rel=\"shortcut icon\" href=\"favicon.ico /\">\n"; 
echo "</head>\n"; 
echo "<body>\n"; 
echo "<div id=\"outerWrapper\">\n"; 
echo "  <div id=\"header\">\n"; 
echo "    <div class=\"main\">          \n"; 
echo "        <!-- Search form --> \n"; 
echo "        <div id=\"search\">\n"; 
echo "            <form action=\"http://www.i-tech-system.com/search.php\" method=\"get\">\n"; 
echo "            	<div>\n"; 
echo "                    <input type=\"hidden\" name=\"cx\" value=\"partner-pub-7526690253327491:69imp65c55c\" />";
echo "                    <input type=\"hidden\" name=\"cof\" value=\"FORID:10\" />";
echo "                    <input type=\"hidden\" name=\"ie\" value=\"UTF-8\" />";
echo "                    <input type=\"text\" size=\"30\" name=\"q\" id=\"search-input\" />\n"; 
echo "					<input type=\"submit\" name=\"sa\" id=\"search-submit\" />\n"; 
echo "            	\n"; 
echo "				</div>\n"; 
echo "            </form>\n"; 
echo "        </div> <!-- /search -->\n"; 
echo "    </div> <!-- /main -->\n"; 
echo "</div> <!-- /header -->\n";
}
?>